[package]
name = "noosphere"
version = "0.2.0"
edition = "2021"
description = "A high-level package for dealing with accessing the Noosphere"
keywords = ["noosphere"]
categories = ["filesystem"]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[profile.release]
opt-level = 'z'
lto = true

[features]
headers = ["safer-ffi/headers"]

[dependencies]
thiserror = "^1"
lazy_static = "^1"
async-trait = "~0.1"
tracing = "~0.1"
url = { version = "^2", features = ["serde"] }
subtext = { version = "~0.3" }
log = "~0.4"
cid.workspace = true
async-recursion = "^1"
async-std = "^1"
# NOTE: async-once-cell 0.4.0 shipped unstable feature usage
async-once-cell = "~0.3"
anyhow.workspace = true
fastcdc = "^1"
futures = "~0.3"
fvm_ipld_amt = "~0.4"
serde = "^1"
byteorder = "^1.4"
base64 = "~0.13"
ed25519-zebra = "^3"
rand = "~0.8"
once_cell = "^1"
serde_ipld_dagcbor = "~0.2"
tiny-bip39 = "^1"
crdts = "^7"
tokio-stream.workspace = true
libipld-core = "~0.14"
libipld-cbor = "~0.14"

noosphere-storage = { path = "../noosphere-storage" }
noosphere-collections = { path = "../noosphere-collections" }

noosphere-core = { version = "0.2.0", path = "../noosphere-core" }
noosphere-fs = { version = "0.1.0", path = "../noosphere-fs" }
noosphere-api = { version = "0.3.0", path = "../noosphere-api" }
ucan = { version = "0.7.0-alpha.1" }
ucan-key-support = { version = "0.7.0-alpha.1" }

[dev-dependencies]
libipld-core = "~0.14"
wasm-bindgen-test = "~0.3"
serde_bytes = "~0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
safer-ffi = { version = "~0.0.10", features = ["proc_macros"] }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "^1", features = ["sync"] }
rexie = { version = "~0.4" }
wasm-bindgen = "~0.2"
js-sys = "~0.3"
tracing-wasm = "~0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "~0.3"
features = [
  "CryptoKey",
]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
temp-dir = "0.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "~0.3"
witty-phrase-generator = "~0.2"
